package com.startdt.android.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.startdt.android.db.table.MagicBaseConfig;

import com.startdt.android.db.dao.MagicBaseConfigDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig magicBaseConfigDaoConfig;

    private final MagicBaseConfigDao magicBaseConfigDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        magicBaseConfigDaoConfig = daoConfigMap.get(MagicBaseConfigDao.class).clone();
        magicBaseConfigDaoConfig.initIdentityScope(type);

        magicBaseConfigDao = new MagicBaseConfigDao(magicBaseConfigDaoConfig, this);

        registerDao(MagicBaseConfig.class, magicBaseConfigDao);
    }
    
    public void clear() {
        magicBaseConfigDaoConfig.clearIdentityScope();
    }

    public MagicBaseConfigDao getMagicBaseConfigDao() {
        return magicBaseConfigDao;
    }

}
